import Header from './components/Header';
import Form from './components/Form';

import type { Metadata } from 'next';
import { PrismaClient } from '@prisma/client';
import { notFound } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Reserve',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: 'https://static-00.iconduck.com/assets.00/next-js-icon-2048x2048-5dqjgeku.png' }],
  },
};

const prisma = new PrismaClient();

const fetchRestaurant = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
  });

  if (!restaurant) {
    return notFound();
  }

  return restaurant;
};

const ReservationPage = async ({
  params,
  searchParams,
}: {
  params: {
    slug: string;
  },
  searchParams: {
    date: string;
    partySize: string;
  }
}) => {
  const restaurant = await fetchRestaurant(params.slug);

  return (
    <>
      <div className="border-t h-screen">
        <div className="py-9 w-3/5 m-auto">
          <Header name={restaurant?.name} image={restaurant?.main_image} partySize={searchParams.partySize} date={searchParams.date} />
          <Form />
        </div>
      </div>
    </>
  );
};

export default ReservationPage;
